### 필요 열 생성 및 에너지 절감 필요 공동주택 선정 
- 단지분류 열 생성
- 세대별로 데이터 셋 분리 
- 단지분류가 "아파트"인 값만 추출
- 2010년 이하에 준공된 아파트 추출 
- 2021 상반기 세대당 월별 전기공용 평균 값 추출
- 2021 상반기 세대당 월별 전기공용 평균 기준으로 이상 단지 탐지 

**분석 대상 선별 후, 엑셀 작업**
- #22 Graph. 에너지 절감 필요 아파트 비율
- #23 Table. 에너지 절감 필요 아파트 가명칭

**분석 대상** 
- 다른 단지분류를 제외한 '아파트'에 해당하는 값만 대상으로 이상치 추출
- 10년 이상된 아파트 대상으로 이상치 탐지 
- 2021년 상반기 가구별 전기공용 평균 기준

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("아파트전체정보_ver0.2.csv", engine = 'python')

In [ ]:
df_basic = pd.read_csv("단지기본정보_ver3.csv", engine = 'python')

**아파트전체정보에 단지분류 열 추가**

In [ ]:
df['단지분류'] = ''

In [ ]:
for i in range(len(df_basic)):
    for j in range(len(df)):
        if df.loc[j, '가명칭'] == df_basic.loc[i, '가명칭']:
            df.loc[j, '단지분류'] = df_basic.loc[i, '단지분류']

In [ ]:
df.to_csv("아파트전체정보_ver0.2.csv", index = False, encoding = 'cp949')

**아파트만 추출**

In [ ]:
df_아파트 = df[df['단지분류'] == '아파트']

In [ ]:
df_아파트.단지분류.unique()

array(['아파트'], dtype=object)

In [ ]:
len(df_아파트.가명칭.unique())

380

In [ ]:
len(df_아파트[df_아파트['사용승인년도_범위'] <= 2010].가명칭.unique())

308

**세대별로 분리**
- 공동주택 중 아파트의 세대별로 분리

In [ ]:
groups = df_아파트.groupby(df_아파트.세대수_범위)

In [ ]:
df300 = groups.get_group(300)
df500 = groups.get_group(500)
df700 = groups.get_group(700)
df900 = groups.get_group(900)
df1100 = groups.get_group(1100)
df1300 = groups.get_group(1300)
df4000 = groups.get_group(4000)

In [ ]:
df300.to_csv("300세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df500.to_csv("500세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df700.to_csv("700세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df900.to_csv("900세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df1100.to_csv("1100세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df1300.to_csv("1300세대_아파트_ver2.csv", index = False, encoding = 'cp949')
df4000.to_csv("4000세대_아파트_ver2.csv", index = False, encoding = 'cp949')

In [ ]:
print('300세대 아파트 공용전기료 평균', df300['전기공용_우리단지총액'].mean())
print('500세대 아파트 공용전기료 평균', df500['전기공용_우리단지총액'].mean())
print('700세대 아파트 공용전기료 평균', df700['전기공용_우리단지총액'].mean())
print('900세대 아파트 공용전기료 평균', df900['전기공용_우리단지총액'].mean())
print('1100세대 아파트 공용전기료 평균', df1100['전기공용_우리단지총액'].mean())
print('1300세대 아파트 공용전기료 평균', df1300['전기공용_우리단지총액'].mean())
print('4000세대 아파트 공용전기료 평균', df4000['전기공용_우리단지총액'].mean())

300세대 아파트 공용전기료 평균 1078420.486818346
500세대 아파트 공용전기료 평균 3166386.4136636634
700세대 아파트 공용전기료 평균 2807507.2862225096
900세대 아파트 공용전기료 평균 3763052.461838006
1100세대 아파트 공용전기료 평균 6704542.161123853
1300세대 아파트 공용전기료 평균 5988345.879061372
4000세대 아파트 공용전기료 평균 10701396.621046228

**2010년이하 아파트전체정보 추출**

In [ ]:
df300_10이하 = df300[df300['사용승인년도_범위'] <= 2010].copy()

In [ ]:
df500_10이하 = df500[df500['사용승인년도_범위'] <= 2010].copy()
df700_10이하 = df700[df700['사용승인년도_범위'] <= 2010].copy()
df900_10이하 = df900[df900['사용승인년도_범위'] <= 2010].copy()
df1100_10이하 = df1100[df1100['사용승인년도_범위'] <= 2010].copy()
df1300_10이하 = df1300[df1300['사용승인년도_범위'] <= 2010].copy()
df4000_10이하 = df4000[df4000['사용승인년도_범위'] <= 2010].copy()

In [ ]:
print(df300_10이하.사용승인년도.unique())
print(df500_10이하.사용승인년도.unique())
print(df700_10이하.사용승인년도.unique())
print(df900_10이하.사용승인년도.unique())
print(df1100_10이하.사용승인년도.unique())
print(df1300_10이하.사용승인년도.unique())
print(df4000_10이하.사용승인년도.unique())

[2002 2006 2000 2003 2007 1997 1985 1995 1999 1986 1992 2004 2005 1984
 1991 1989 1990 2001 1996 1998]
[2007 1990 1999 1985 2000 1979 1987 1978 1994 1991 1986 1998 2006 1995
 1992 1993 2005 2004 2008 2001 1989]
[1989 1985 2007 2006 1991 1990 1996 1992 2004 1983 1994 1993 1997 2005
 2002 2001 2000 2003 1987 1999]
[2007 2006 2008 2003 1987 1992 1994 1989 1978 1981 1986 2005 1988 1990
 1997 1995 1996 1991 2002 2004 2001 2000 1993 1998]
[2006 1990 1999 1998 2001 1994 2007 2008 2005 1995 1991 1987 2000 1993
 1997 1992 2004 2009]
[2007 2000 2005 1993 1994 1999 1998 1991 1995 1987]
[1992 1990 2003 2000 1986 1995 1994 1998 1993 1999 1997 1991 2002 2004
 1996]

**세대별 월별 전기공용금액 열 생성**

In [ ]:
df300_10이하['세대별_월별_전기공용'] = ''

In [ ]:
df300_10이하['세대별_월별_전기공용'] = df300_10이하['전기공용_우리단지총액'] / df300_10이하['세대수']

In [ ]:
df300_10이하

,명칭(단지코드),부과년월,전기공용_우리단지총액,부과년도,부과월,단지분류,법정동주소,사용승인일,동수,세대수,...,세대전기계약방식,승강기대수,지상,지하,주차관제.홈네트워크,CCTV대수,부대복리시설수,반기,분기,세대별_월별_전기공용
2076,A30009202,201801.0,249900.0,2018.0,1.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,964.864865
2077,A30009202,201802.0,-464790.0,2018.0,2.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-1794.555985
2078,A30009202,201803.0,79600.0,2018.0,3.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,307.335907
2079,A30009202,201804.0,386590.0,2018.0,4.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,1492.625483
2080,A30009202,201805.0,17512.0,2018.0,5.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,67.613900
2081,A30009202,201806.0,-124860.0,2018.0,6.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,-482.084942
2082,A30009202,201807.0,-23870.0,2018.0,7.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,-92.162162
2083,A30009202,201808.0,-88790.0,2018.0,8.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,-342.818533
2084,A30009202,201809.0,-254590.0,2018.0,9.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,-982.972973
2085,A30009202,201810.0,17590.0,2018.0,10.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,67.915058
2086,A30009202,201811.0,17522.0,2018.0,11.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,67.652510
2087,A30009202,201812.0,-181310.0,2018.0,12.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,-700.038610
2088,A30009202,201901.0,-58790.0,2019.0,1.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-226.988417
2089,A30009202,201902.0,-293070.0,2019.0,2.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-1131.544402
2090,A30009202,201903.0,81160.0,2019.0,3.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,313.359073
2091,A30009202,201904.0,227960.0,2019.0,4.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,880.154440
2092,A30009202,201905.0,121580.0,2019.0,5.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,469.420849
2093,A30009202,201906.0,67810.0,2019.0,6.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,261.814672
2094,A30009202,201907.0,37130.0,2019.0,7.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,143.359073
2095,A30009202,201908.0,36020.0,2019.0,8.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,139.073359
2096,A30009202,201909.0,-401150.0,2019.0,9.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,3,-1548.841699
2097,A30009202,201910.0,-38450.0,2019.0,10.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,-148.455598
2098,A30009202,201911.0,-248050.0,2019.0,11.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,-957.722008
2099,A30009202,201912.0,21930.0,2019.0,12.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,하반기,4,84.671815
2100,A30009202,202001.0,-171370.0,2020.0,1.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-661.660232
2101,A30009202,202002.0,-177150.0,2020.0,2.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-683.976834
2102,A30009202,202003.0,-96580.0,2020.0,3.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,1,-372.895753
2103,A30009202,202004.0,-71570.0,2020.0,4.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,-276.332046
2104,A30009202,202005.0,-178150.0,2020.0,5.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,-687.837838
2105,A30009202,202006.0,-6430.0,2020.0,6.0,아파트,대전광역시 동구 가양동 162-11,20020731,1,259,...,단일계약,3,36.0,150,무,27,2,상반기,2,-24.826255
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17418,A30681901,201901.0,759350.0,2019.0,1.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,3796.750000
17419,A30681901,201902.0,503860.0,2019.0,2.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,2519.300000
17420,A30681901,201903.0,397180.0,2019.0,3.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,1985.900000
17421,A30681901,201904.0,408920.0,2019.0,4.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,2044.600000
17422,A30681901,201905.0,411840.0,2019.0,5.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,2059.200000
17423,A30681901,201906.0,342990.0,2019.0,6.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1714.950000
17424,A30681901,201907.0,518580.0,2019.0,7.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,2592.900000
17425,A30681901,201908.0,427030.0,2019.0,8.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,2135.150000
17426,A30681901,201909.0,421210.0,2019.0,9.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,2106.050000
17427,A30681901,201910.0,412650.0,2019.0,10.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,2063.250000
17428,A30681901,201911.0,391440.0,2019.0,11.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,1957.200000
17429,A30681901,201912.0,406060.0,2019.0,12.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,2030.300000
17430,A30681901,202001.0,431710.0,2020.0,1.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,2158.550000
17431,A30681901,202002.0,382820.0,2020.0,2.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,1914.100000
17432,A30681901,202003.0,363900.0,2020.0,3.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,1819.500000
17433,A30681901,202004.0,332860.0,2020.0,4.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1664.300000
17434,A30681901,202005.0,358580.0,2020.0,5.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1792.900000
17435,A30681901,202006.0,313480.0,2020.0,6.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1567.400000
17436,A30681901,202007.0,325230.0,2020.0,7.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,1626.150000
17437,A30681901,202008.0,332790.0,2020.0,8.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,1663.950000
17438,A30681901,202009.0,283640.0,2020.0,9.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,3,1418.200000
17439,A30681901,202010.0,338840.0,2020.0,10.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,1694.200000
17440,A30681901,202011.0,311500.0,2020.0,11.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,1557.500000
17441,A30681901,202012.0,399560.0,2020.0,12.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,하반기,4,1997.800000
17442,A30681901,202101.0,383420.0,2021.0,1.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,1917.100000
17443,A30681901,202102.0,400420.0,2021.0,2.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,2002.100000
17444,A30681901,202103.0,398490.0,2021.0,3.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,1,1992.450000
17445,A30681901,202104.0,387190.0,2021.0,4.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1935.950000
17446,A30681901,202105.0,274410.0,2021.0,5.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,1372.050000
17447,A30681901,202106.0,521790.0,2021.0,6.0,아파트,대전광역시 대덕구 오정동 464-1,19961005,2,200,...,단일계약,9,89.0,68,무,32,4,상반기,2,2608.950000

In [ ]:
df500_10이하['세대별_월별_전기공용'] = ''

In [ ]:
df500_10이하['세대별_월별_전기공용'] = df500_10이하['전기공용_우리단지총액'] / df500_10이하['세대수']

In [ ]:
df700_10이하['세대별_월별_전기공용'] = ''

In [ ]:
df700_10이하['세대별_월별_전기공용'] = df700_10이하['전기공용_우리단지총액'] / df700_10이하['세대수']

In [ ]:
df900_10이하['세대별_월별_전기공용'] = ''
df900_10이하['세대별_월별_전기공용'] = df900_10이하['전기공용_우리단지총액'] / df900_10이하['세대수']

In [ ]:
df1100_10이하['세대별_월별_전기공용'] = ''
df1100_10이하['세대별_월별_전기공용'] = df1100_10이하['전기공용_우리단지총액'] / df1100_10이하['세대수']

In [ ]:
df1300_10이하['세대별_월별_전기공용'] = ''
df1300_10이하['세대별_월별_전기공용'] = df1300_10이하['전기공용_우리단지총액'] / df1300_10이하['세대수']

In [ ]:
df4000_10이하['세대별_월별_전기공용'] = ''
df4000_10이하['세대별_월별_전기공용'] = df4000_10이하['전기공용_우리단지총액'] / df4000_10이하['세대수']

In [ ]:
df4000_10이하.세대수_범위.unique()

array([4000], dtype=int64)

In [ ]:
df1300_10이하.세대수_범위.unique()

array([1300], dtype=int64)

In [ ]:
df1100_10이하.세대수_범위.unique()

array([1100], dtype=int64)

In [ ]:
df900_10이하.세대수_범위.unique()

array([900], dtype=int64)

In [ ]:
df700_10이하.세대수_범위.unique()

array([700], dtype=int64)

In [ ]:
df500_10이하.세대수_범위.unique()

array([500], dtype=int64)

In [ ]:
df300_10이하.세대수_범위.unique()

array([300], dtype=int64)

**2021년 상반기 세대당 월별 전기공용 평균 구하기**

In [ ]:
grouped300 = df300_10이하[df300_10이하['부과년도'] == 2021].groupby(['가명칭'])
df300_2021 = pd.DataFrame(grouped300['세대별_월별_전기공용'].mean())

In [ ]:
grouped500 = df500_10이하[df500_10이하['부과년도'] == 2021].groupby(['가명칭'])
df500_2021 = pd.DataFrame(grouped500['세대별_월별_전기공용'].mean())

In [ ]:
grouped700 = df700_10이하[df700_10이하['부과년도'] == 2021].groupby(['가명칭'])
df700_2021 = pd.DataFrame(grouped700['세대별_월별_전기공용'].mean())

In [ ]:
grouped900 = df900_10이하[df900_10이하['부과년도'] == 2021].groupby(['가명칭'])
df900_2021 = pd.DataFrame(grouped900['세대별_월별_전기공용'].mean())

In [ ]:
grouped1100 = df1100_10이하[df1100_10이하['부과년도'] == 2021].groupby(['가명칭'])
df1100_2021 = pd.DataFrame(grouped1100['세대별_월별_전기공용'].mean())

In [ ]:
grouped1300 = df1300_10이하[df1300_10이하['부과년도'] == 2021].groupby(['가명칭'])
df1300_2021 = pd.DataFrame(grouped1300['세대별_월별_전기공용'].mean())

In [ ]:
grouped4000 = df4000_10이하[df4000_10이하['부과년도'] == 2021].groupby(['가명칭'])
df4000_2021 = pd.DataFrame(grouped4000['세대별_월별_전기공용'].mean())

### 에너지 절감 필요 공동주택 선정
- IQR 그래프를 활용하여 이상치 값 추출 즉, 에너지 사용료가 많이 나가는 아파트 추출 
- 세대수별로 나누어 각각 이상치 판단

**IQR그래프 / 이상치 탐지**
- IQR 코드 
- 데이터 셋별로 이상치 탐지 
- 2010년 이하, 세대별 (300, 700, 900, 1100, 1300, 4000)
- 기준 값 : 2021년 상반기 "세대별 월별 전기공용" 평균 
- 평균의 분포 > 이상치 탐지

**300세대 이상치**
- Q3 이상 (75% 이상)
- Q3 + 1.5*IQR (극단 이상치)

In [ ]:
Q3_300_2021 = df300_2021.quantile(.75)['세대별_월별_전기공용']
IQR_300_2021 = df300_2021.quantile(.75)['세대별_월별_전기공용'] - df300_2021.quantile(.25)['세대별_월별_전기공용']

In [ ]:
Q3_300_2021_단지명 = []

# 이상치 Q3 기준 
for i in df300_2021.index:
    if df300_2021.loc[i, '세대별_월별_전기공용']  > Q3_300_2021:
        Q3_300_2021_단지명.append(i)

In [ ]:
Outliers_300_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df300_2021.index:
    if df300_2021.loc[i, '세대별_월별_전기공용']  > Q3_300_2021 + 1.5*IQR_300_2021:
        Outliers_300_2021_단지명.append(i)

**500세대 이상치**

In [ ]:
Q3_500_2021 = df500_2021.quantile(.75)['세대별_월별_전기공용']
IQR_500_2021 = df500_2021.quantile(.75)['세대별_월별_전기공용'] - df500_2021.quantile(.25)['세대별_월별_전기공용']

Q3_500_2021_단지명 = []

# 이상치 Q3 기준 
for i in df500_2021.index:
    if df500_2021.loc[i, '세대별_월별_전기공용']  > Q3_500_2021:
        Q3_500_2021_단지명.append(i)
        
Outliers_500_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df500_2021.index:
    if df500_2021.loc[i, '세대별_월별_전기공용']  > Q3_500_2021 + 1.5*IQR_500_2021:
        Outliers_500_2021_단지명.append(i)

**700세대 이상치**

In [ ]:
Q3_700_2021 = df700_2021.quantile(.75)['세대별_월별_전기공용']
IQR_700_2021 = df700_2021.quantile(.75)['세대별_월별_전기공용'] - df700_2021.quantile(.25)['세대별_월별_전기공용']

Q3_700_2021_단지명 = []

# 이상치 Q3 기준 
for i in df700_2021.index:
    if df700_2021.loc[i, '세대별_월별_전기공용']  > Q3_700_2021:
        Q3_700_2021_단지명.append(i)
        
Outliers_700_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df700_2021.index:
    if df700_2021.loc[i, '세대별_월별_전기공용']  > Q3_700_2021 + 1.5*IQR_700_2021:
        Outliers_700_2021_단지명.append(i)

**900세대 이상치**

In [ ]:
Q3_900_2021 = df900_2021.quantile(.75)['세대별_월별_전기공용']
IQR_900_2021 = df900_2021.quantile(.75)['세대별_월별_전기공용'] - df900_2021.quantile(.25)['세대별_월별_전기공용']

Q3_900_2021_단지명 = []

# 이상치 Q3 기준 
for i in df900_2021.index:
    if df900_2021.loc[i, '세대별_월별_전기공용']  > Q3_900_2021:
        Q3_900_2021_단지명.append(i)
        
Outliers_900_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df900_2021.index:
    if df900_2021.loc[i, '세대별_월별_전기공용']  > Q3_900_2021 + 1.5*IQR_900_2021:
        Outliers_900_2021_단지명.append(i)

**1100세대 이상치**

In [ ]:
Q3_1100_2021 = df1100_2021.quantile(.75)['세대별_월별_전기공용']
IQR_1100_2021 = df1100_2021.quantile(.75)['세대별_월별_전기공용'] - df1100_2021.quantile(.25)['세대별_월별_전기공용']

Q3_1100_2021_단지명 = []

# 이상치 Q3 기준 
for i in df1100_2021.index:
    if df1100_2021.loc[i, '세대별_월별_전기공용']  > Q3_1100_2021:
        Q3_1100_2021_단지명.append(i)
        
Outliers_1100_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df1100_2021.index:
    if df1100_2021.loc[i, '세대별_월별_전기공용']  > Q3_1100_2021 + 1.5*IQR_1100_2021:
        Outliers_1100_2021_단지명.append(i)

**1300세대 이상치**

In [ ]:
Q3_1300_2021 = df1300_2021.quantile(.75)['세대별_월별_전기공용']
IQR_1300_2021 = df1300_2021.quantile(.75)['세대별_월별_전기공용'] - df1300_2021.quantile(.25)['세대별_월별_전기공용']

Q3_1300_2021_단지명 = []

# 이상치 Q3 기준 
for i in df1300_2021.index:
    if df1300_2021.loc[i, '세대별_월별_전기공용']  > Q3_1300_2021:
        Q3_1300_2021_단지명.append(i)
        
Outliers_1300_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df1300_2021.index:
    if df1300_2021.loc[i, '세대별_월별_전기공용']  > Q3_1300_2021 + 1.5*IQR_1300_2021:
        Outliers_1300_2021_단지명.append(i)

**4000세대 이상치**

In [ ]:
Q3_4000_2021 = df4000_2021.quantile(.75)['세대별_월별_전기공용']
IQR_4000_2021 = df4000_2021.quantile(.75)['세대별_월별_전기공용'] - df4000_2021.quantile(.25)['세대별_월별_전기공용']

Q3_4000_2021_단지명 = []

# 이상치 Q3 기준 
for i in df4000_2021.index:
    if df4000_2021.loc[i, '세대별_월별_전기공용']  > Q3_4000_2021:
        Q3_4000_2021_단지명.append(i)
        
Outliers_4000_2021_단지명 = []

# 이상치 Q3 + 1.5*IQR 기준 
for i in df4000_2021.index:
    if df4000_2021.loc[i, '세대별_월별_전기공용']  > Q3_4000_2021 + 1.5*IQR_4000_2021:
        Outliers_4000_2021_단지명.append(i)

**Q3 이상의 이상치**

In [ ]:
print("300세대 Q3 이상치 : ", Q3_300_2021_단지명)
print("500세대 Q3 이상치 : ", Q3_500_2021_단지명)
print("700세대 Q3 이상치 : ", Q3_700_2021_단지명)
print("900세대 Q3 이상치 : ", Q3_900_2021_단지명)
print("1100세대 Q3 이상치 : ", Q3_1100_2021_단지명)
print("1300세대 Q3 이상치 : ", Q3_1300_2021_단지명)
print("4000세대 Q3 이상치 : ", Q3_4000_2021_단지명)

300세대 Q3 이상치 :  ['구암2', '도룡3', '도마3', '문화12', '변3', '산성2', '선화1', '오정3', '용문1', '용문2', '용운5', '읍내1', '인2', '태평10', '하기5']
500세대 Q3 이상치 :  ['관평10', '관평4', '관평8', '관평9', '교촌2', '둔산16', '목상1', '복수5', '용산1', '용산2', '용산3', '용산4', '태평2', '하기1']
700세대 Q3 이상치 :  ['가오6', '관평2', '관평3', '관평5', '괴정1', '노은3', '둔산13', '둔산15', '월평7', '유천1', '지족13', '지족19', '지족20', '지족21', '태평7', '홍도1']
900세대 Q3 이상치 :  ['가수원2', '관저6', '관평7', '노은1', '둔산9', '복수6', '신성3', '원내1', '원내3', '월평3', '천1', '하기2']
1100세대 Q3 이상치 :  ['관저1', '관저8', '관평1', '관평6', '문화2', '복수2', '산성4', '삼성2']
1300세대 Q3 이상치 :  ['관저18', '대성1', '둔산12', '태평12', '태평3']
4000세대 Q3 이상치 :  ['갈마6', '도마2', '둔산10', '둔산23', '둔산26', '목3', '송촌2', '전민4', '정림2']

In [ ]:
Q3_300_2021_단지명_df = pd.DataFrame(Q3_300_2021_단지명).rename({0:'300세대_Q3_가구별_전기공용'}, axis =1)
Q3_500_2021_단지명_df = pd.DataFrame(Q3_500_2021_단지명).rename({0:'500세대_Q3_가구별_전기공용'}, axis =1)
Q3_700_2021_단지명_df = pd.DataFrame(Q3_700_2021_단지명).rename({0:'700세대_Q3_가구별_전기공용'}, axis =1)
Q3_900_2021_단지명_df = pd.DataFrame(Q3_900_2021_단지명).rename({0:'900세대_Q3_가구별_전기공용'}, axis =1)
Q3_1100_2021_단지명_df = pd.DataFrame(Q3_1100_2021_단지명).rename({0:'1100세대_Q3_가구별_전기공용'}, axis =1)
Q3_1300_2021_단지명_df = pd.DataFrame(Q3_1300_2021_단지명).rename({0:'1300세대_Q3_가구별_전기공용'}, axis =1)
Q3_4000_2021_단지명_df = pd.DataFrame(Q3_4000_2021_단지명).rename({0:'4000세대_Q3_가구별_전기공용'}, axis =1)

In [ ]:
whole_q3 = pd.concat([Q3_300_2021_단지명_df, Q3_500_2021_단지명_df, Q3_700_2021_단지명_df, Q3_900_2021_단지명_df, Q3_1100_2021_단지명_df, Q3_1300_2021_단지명_df,Q3_4000_2021_단지명_df ], axis=1)

In [ ]:
whole_q3.to_csv("가구별_전기공용_Q3_아파트만_ver3.csv", index=False, encoding = 'cp949')

**Q3 + 1.5*IQR 이상치**

In [ ]:
print("300세대 Q3 + 1.5*IQR 이상치 : ", Outliers_300_2021_단지명)
print("500세대 Q3 + 1.5*IQR 이상치 : ", Outliers_500_2021_단지명)
print("700세대 Q3 + 1.5*IQR 이상치 : ", Outliers_700_2021_단지명)
print("900세대 Q3 + 1.5*IQR 이상치 : ", Outliers_900_2021_단지명)
print("1100세대 Q3 + 1.5*IQR 이상치 : ", Outliers_1100_2021_단지명)
print("1300세대 Q3 + 1.5*IQR 이상치 : ", Outliers_1300_2021_단지명)
print("4000세대 Q3 + 1.5*IQR 이상치 : ", Outliers_4000_2021_단지명)

300세대 Q3 + 1.5*IQR 이상치 :  ['도룡3', '읍내1', '하기5']
500세대 Q3 + 1.5*IQR 이상치 :  ['관평10', '관평9', '목상1', '용산2', '용산3', '태평2']
700세대 Q3 + 1.5*IQR 이상치 :  ['관평3']
900세대 Q3 + 1.5*IQR 이상치 :  ['관저6', '복수6']
1100세대 Q3 + 1.5*IQR 이상치 :  []
1300세대 Q3 + 1.5*IQR 이상치 :  []
4000세대 Q3 + 1.5*IQR 이상치 :  ['도마2']

In [ ]:
Outliers_300_2021_단지명_df = pd.DataFrame(Outliers_300_2021_단지명).rename({0:'300세대_이상치_가구별_전기공용'}, axis =1)
Outliers_500_2021_단지명_df = pd.DataFrame(Outliers_500_2021_단지명).rename({0:'500세대_이상치_가구별_전기공용'}, axis =1)
Outliers_700_2021_단지명_df = pd.DataFrame(Outliers_700_2021_단지명).rename({0:'700세대_이상치_가구별_전기공용'}, axis =1)
Outliers_900_2021_단지명_df = pd.DataFrame(Outliers_900_2021_단지명).rename({0:'900세대_이상치_가구별_전기공용'}, axis =1)
Outliers_1100_2021_단지명_df = pd.DataFrame(Outliers_1100_2021_단지명).rename({0:'1100세대_이상치_가구별_전기공용'}, axis =1)
Outliers_1300_2021_단지명_df = pd.DataFrame(Outliers_1300_2021_단지명).rename({0:'1300세대_이상치_가구별_전기공용'}, axis =1)
Outliers_4000_2021_단지명_df = pd.DataFrame(Outliers_4000_2021_단지명).rename({0:'4000세대_이상치_가구별_전기공용'}, axis =1)

In [ ]:
whole_outlier = pd.concat([Outliers_300_2021_단지명_df, Outliers_500_2021_단지명_df, Outliers_700_2021_단지명_df, Outliers_900_2021_단지명_df, Outliers_1100_2021_단지명_df, Outliers_1300_2021_단지명_df,Outliers_4000_2021_단지명_df ], axis=1)

In [ ]:
whole_outlier.to_csv("가구별_전기공용_이상치_아파트만_ver3.csv", index = False, encoding = 'cp949')

**Q3 이상치**

In [ ]:
whole_q3

,300세대_Q3_가구별_전기공용,500세대_Q3_가구별_전기공용,700세대_Q3_가구별_전기공용,900세대_Q3_가구별_전기공용,1100세대_Q3_가구별_전기공용,1300세대_Q3_가구별_전기공용,4000세대_Q3_가구별_전기공용
0,구암2,관평10,가오6,가수원2,관저1,관저18,갈마6
1,도룡3,관평4,관평2,관저6,관저8,대성1,도마2
2,도마3,관평8,관평3,관평7,관평1,둔산12,둔산10
3,문화12,관평9,관평5,노은1,관평6,태평12,둔산23
4,변3,교촌2,괴정1,둔산9,문화2,태평3,둔산26
5,산성2,둔산16,노은3,복수6,복수2,NaN,목3
6,선화1,목상1,둔산13,신성3,산성4,NaN,송촌2
7,오정3,복수5,둔산15,원내1,삼성2,NaN,전민4
8,용문1,용산1,월평7,원내3,NaN,NaN,정림2
9,용문2,용산2,유천1,월평3,NaN,NaN,NaN
10,용운5,용산3,지족13,천1,NaN,NaN,NaN
11,읍내1,용산4,지족19,하기2,NaN,NaN,NaN
12,인2,태평2,지족20,NaN,NaN,NaN,NaN
13,태평10,하기1,지족21,NaN,NaN,NaN,NaN
14,하기5,NaN,태평7,NaN,NaN,NaN,NaN
15,NaN,NaN,홍도1,NaN,NaN,NaN,NaN

**Q3 + 1.5*IQR**

In [ ]:
whole_outlier

,300세대_이상치_가구별_전기공용,500세대_이상치_가구별_전기공용,700세대_이상치_가구별_전기공용,900세대_이상치_가구별_전기공용,4000세대_이상치_가구별_전기공용
0,도룡3,관평10,관평3,관저6,도마2
1,읍내1,관평9,NaN,복수6,NaN
2,하기5,목상1,NaN,NaN,NaN
3,NaN,용산2,NaN,NaN,NaN
4,NaN,용산3,NaN,NaN,NaN
5,NaN,태평2,NaN,NaN,NaN

**이상치 단지 탐색**

In [ ]:
whole_outlier.columns

Index(['300세대_이상치_가구별_전기공용', '500세대_이상치_가구별_전기공용', '700세대_이상치_가구별_전기공용',
       '900세대_이상치_가구별_전기공용', '4000세대_이상치_가구별_전기공용'],
      dtype='object')

In [ ]:
out_cnt = 0
for i in whole_outlier.columns:
    out_cnt += whole_outlier[i].notnull().sum()

In [ ]:
out_cnt

13

In [ ]:
final_out = pd.concat([whole_outlier['300세대_이상치_가구별_전기공용'], whole_outlier['500세대_이상치_가구별_전기공용'],  whole_outlier['700세대_이상치_가구별_전기공용'], whole_outlier['900세대_이상치_가구별_전기공용'], whole_outlier['4000세대_이상치_가구별_전기공용']]).dropna().reset_index().drop('index', axis=1).rename({0:"이상치_단지_가명칭"}, axis=1)

In [ ]:
# 극단 이상치 리스트 
for i in final_out['이상치_단지_가명칭'].values:
    print(i)

도룡3
읍내1
하기5
관평10
관평9
목상1
용산2
용산3
태평2
관평3
관저6
복수6
도마2

**극단 이상치 단지에 해당하는 아파트 전체 정보 추출**

In [ ]:
final_whole_out = []

In [ ]:
for j in final_out['이상치_단지_가명칭'].values:
    for i in range(len(df)):
        if df.loc[i, '가명칭'] == j:
            final_whole_out.append(df.loc[i,:])

In [ ]:
final_whole_out = pd.DataFrame(final_whole_out)

In [ ]:
final_whole_out

,명칭(단지코드),부과년월,전기공용_우리단지총액,부과년도,부과월,단지분류,법정동주소,사용승인일,동수,세대수,...,가명칭,세대전기계약방식,승강기대수,지상,지하,주차관제.홈네트워크,CCTV대수,부대복리시설수,반기,분기
13332,A30534002,201801.0,348340.0,2018.0,1.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13333,A30534002,201802.0,7276570.0,2018.0,2.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13334,A30534002,201803.0,1582400.0,2018.0,3.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13335,A30534002,201804.0,1340840.0,2018.0,4.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13336,A30534002,201805.0,1291560.0,2018.0,5.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13337,A30534002,201806.0,4399150.0,2018.0,6.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13338,A30534002,201807.0,7125770.0,2018.0,7.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13339,A30534002,201808.0,9738850.0,2018.0,8.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13340,A30534002,201809.0,72320.0,2018.0,9.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13341,A30534002,201810.0,1416630.0,2018.0,10.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13342,A30534002,201811.0,883110.0,2018.0,11.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13343,A30534002,201812.0,1374320.0,2018.0,12.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13344,A30534002,201901.0,1076290.0,2019.0,1.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13345,A30534002,201902.0,1846490.0,2019.0,2.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13346,A30534002,201903.0,1184670.0,2019.0,3.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13347,A30534002,201904.0,1257270.0,2019.0,4.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13348,A30534002,201905.0,1271020.0,2019.0,5.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13349,A30534002,201906.0,819110.0,2019.0,6.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13350,A30534002,201907.0,529570.0,2019.0,7.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13351,A30534002,201908.0,739540.0,2019.0,8.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13352,A30534002,201909.0,863670.0,2019.0,9.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,3
13353,A30534002,201910.0,955880.0,2019.0,10.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13354,A30534002,201911.0,1214580.0,2019.0,11.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13355,A30534002,201912.0,1126300.0,2019.0,12.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,하반기,4
13356,A30534002,202001.0,852450.0,2020.0,1.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13357,A30534002,202002.0,6557630.0,2020.0,2.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13358,A30534002,202003.0,6310650.0,2020.0,3.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,1
13359,A30534002,202004.0,6605060.0,2020.0,4.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13360,A30534002,202005.0,5988630.0,2020.0,5.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
13361,A30534002,202006.0,6638120.0,2020.0,6.0,아파트,대전광역시 유성구 도룡동 431-6,19891012,3,150,...,도룡3,단일계약,8,134.0,0,무,32,6,상반기,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9732,A30276303,201901.0,11788105.0,2019.0,1.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9733,A30276303,201902.0,11556963.0,2019.0,2.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9734,A30276303,201903.0,9373769.0,2019.0,3.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9735,A30276303,201904.0,9441300.0,2019.0,4.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9736,A30276303,201905.0,8373583.0,2019.0,5.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9737,A30276303,201906.0,8819778.0,2019.0,6.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9738,A30276303,201907.0,5572135.0,2019.0,7.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9739,A30276303,201908.0,67159349.0,2019.0,8.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9740,A30276303,201909.0,48536171.0,2019.0,9.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9741,A30276303,201910.0,44962285.0,2019.0,10.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9742,A30276303,201911.0,9788498.0,2019.0,11.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9743,A30276303,201912.0,55201645.0,2019.0,12.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9744,A30276303,202001.0,60372511.0,2020.0,1.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9745,A30276303,202002.0,60074967.0,2020.0,2.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9746,A30276303,202003.0,53580097.0,2020.0,3.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9747,A30276303,202004.0,54856970.0,2020.0,4.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9748,A30276303,202005.0,48312472.0,2020.0,5.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9749,A30276303,202006.0,50532154.0,2020.0,6.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9750,A30276303,202007.0,41674748.0,2020.0,7.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9751,A30276303,202008.0,60075301.0,2020.0,8.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9752,A30276303,202009.0,57122531.0,2020.0,9.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,3
9753,A30276303,202010.0,47084524.0,2020.0,10.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9754,A30276303,202011.0,53609773.0,2020.0,11.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9755,A30276303,202012.0,57958746.0,2020.0,12.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,하반기,4
9756,A30276303,202101.0,62653820.0,2021.0,1.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9757,A30276303,202102.0,58519180.0,2021.0,2.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9758,A30276303,202103.0,46152573.0,2021.0,3.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,1
9759,A30276303,202104.0,49672259.0,2021.0,4.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9760,A30276303,202105.0,45248443.0,2021.0,5.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2
9761,A30276303,202106.0,47040435.0,2021.0,6.0,아파트,대전광역시 서구 도마동 193,19860501,15,1475,...,도마2,단일계약,46,1042.0,0,무,168,4,상반기,2

In [ ]:
final_whole_out.to_csv("이상치_단지_전체정보_아파트만_ver3.csv", index = False, encoding = 'cp949')

**극단 이상치와 시설 특성 비교**

In [ ]:
final_whole_out['세대전기계약방식'].groupby(final_whole_out['가명칭']).value_counts()

가명칭   세대전기계약방식
관저6   종합계약        42
관평10  종합계약        42
관평3   종합계약        42
관평9   종합계약        42
도룡3   단일계약        42
도마2   단일계약        42
목상1   단일계약        42
복수6   단일계약        42
용산2   종합계약        42
용산3   단일계약        42
읍내1   단일계약        42
태평2   단일계약        42
하기5   단일계약        42
Name: 세대전기계약방식, dtype: int64

In [ ]:
final_whole_out_fac = final_whole_out.groupby('세대수_범위').mean().loc[:, ['전기공용_우리단지총액','사용승인년도','승강기대수', '지상','지하','부대복리시설수']]

In [ ]:
df_fac = df.groupby('세대수_범위').mean().loc[:, ['전기공용_우리단지총액','사용승인년도', '승강기대수', '지상','지하','부대복리시설수']]

In [ ]:
final_whole_out_fac['지하비율'] = ''

In [ ]:
final_whole_out_fac['지하비율'] = final_whole_out_fac['지하'] / (final_whole_out_fac['지하'] + final_whole_out_fac['지상'])

In [ ]:
final_whole_out_fac

,전기공용_우리단지총액,사용승인년도,승강기대수,지상,지하,부대복리시설수,지하비율
세대수_범위,,,,,,,
300,4.584864e+06,1997.333333,6.666667,104.666667,145.000000,5.0,0.580774
500,9.322997e+06,2004.666667,17.000000,168.166667,508.666667,4.0,0.751539
700,9.598760e+06,2006.000000,40.000000,228.000000,743.000000,7.0,0.765191
900,6.681768e+06,2003.500000,24.500000,285.000000,518.000000,4.5,0.645081
4000,3.234212e+07,1986.000000,46.000000,1042.000000,0.000000,4.0,0.000000

In [ ]:
df_fac['지하비율'] = ''

In [ ]:
df_fac['지하비율'] = df_fac['지하'] / (df_fac['지하'] + df_fac['지상'])

In [ ]:
df_fac

,전기공용_우리단지총액,사용승인년도,승강기대수,지상,지하,부대복리시설수,지하비율
세대수_범위,,,,,,,
300,1.660867e+06,2003.231657,5.394324,63.729886,148.676973,3.458468,0.699963
500,3.376320e+06,1999.303226,11.713978,151.281720,274.793548,5.027957,0.644941
700,2.924458e+06,2000.824622,18.413098,238.344773,441.929471,5.895151,0.649634
900,4.237908e+06,1999.632184,22.032950,316.693487,516.121073,5.962452,0.619731
1100,6.938607e+06,2002.516797,29.367861,357.070549,742.210526,6.563830,0.675178
1300,5.988346e+06,2002.364621,30.969314,381.503610,958.388087,6.222022,0.715273
4000,1.070140e+07,1997.838200,51.870438,895.874696,1059.626521,5.534672,0.541870

**이상 단지 수와 전체 공동주택 단지 수**

In [ ]:
len(df['가명칭'].unique())

429

In [ ]:
len(final_whole_out['가명칭'].unique())

13